export const VACCINE_CODES = {
  BCG: { full: "Tuberculosis Vaccine", short: "BCG" },
  HepB: { full: "Hepatitis B Vaccine", short: "HepB" },
  OPV0: { full: "Oral Polio Vaccine, Zero dose", short: "OPV0" },
  OPV1: { full: "Oral Polio Vaccine, 1st dose", short: "OPV1" },
  OPV2: { full: "Oral Polio Vaccine, 2nd dose", short: "OPV2" },
  OPV3: { full: "Oral Polio Vaccine, 3rd dose", short: "OPV3" },
  Penta1: { full: "Pentavalent Vaccine, 1st dose", short: "Penta1" },
  Penta2: { full: "Pentavalent Vaccine, 2nd dose", short: "Penta2" },
  Penta3: { full: "Pentavalent Vaccine, 3rd dose", short: "Penta3" },
  PCV1: { full: "Pneumococcal Conjugate Vaccine, 1st dose", short: "PCV1" },
  PCV2: { full: "Pneumococcal Conjugate Vaccine, 2nd dose", short: "PCV2" },
  PCV3: { full: "Pneumococcal Conjugate Vaccine, 3rd dose", short: "PCV3" },
  Rota1: { full: "Rotavirus Vaccine, 1st dose", short: "Rota1" },
  Rota2: { full: "Rotavirus Vaccine, 2nd dose", short: "Rota2" },
  Rota3: { full: "Rotavirus Vaccine, 3rd dose", short: "Rota3" },
  IPV1: { full: "Inactivated Polio Vaccine, 1st dose", short: "IPV1" },
  IPV2: { full: "Inactivated Polio Vaccine, 2nd dose", short: "IPV2" },
  Measles1: { full: "Measles Vaccine, 1st dose", short: "Measles1" },
  Measles2: { full: "Measles Vaccine, 2nd dose", short: "Measles2" },
  VitA1: { full: "Vitamin A Supplement, 1st dose", short: "VitA1" },
  VitA2: { full: "Vitamin A Supplement, 2nd dose", short: "VitA2" },
  YellowFever: { full: "Yellow Fever Vaccine", short: "YellowFever" },
  Meningitis: { full: "Meningitis Vaccine", short: "Meningitis" },
};
